### ISSUE TITLE
e-mail addresses are erroneously interpreted as mentions

### ISSUE THREAD

**Issue by FND** [innoq/feedworker#1]
a statuses message like ...

> hello foo@example.org world

... leads to a notification to example@example.org (i.e. it's interpreted as `@example`

**Comment by pschirmacher** [comment]
Feedworker identifies mentions like this: https://github.com/innoq/feedworker/blob/master/src/feedworker/statuses.clj#L59

IMHO, that should be fine and it doesn't find a mention in a message like "hello <a href='mailto:foo@example.org'>foo@example.org</a>".

It does however find a mention here: "hello foo@<a href='whatever'>example</a>.org". I would argue that's a bug in https://github.com/innoq/statuses, though.

**Comment by FND** [comment]
agreed: innoq/statuses#96
